project_id = "ezqiyuqqxuhkbhwrpaoz"

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-minutes-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-minutes-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false